* File: ref_inv_pex.sp.REF_INV.pxi
* Created: Tue Sep 12 01:58:05 2017
* 
x_PM_REF_INV_IN N_IN_M0_g N_IN_M1_g IN PM_REF_INV_IN
x_PM_REF_INV_GND N_GND_M0_b GND N_GND_M0_s PM_REF_INV_GND
x_PM_REF_INV_VDD N_VDD_M1_b VDD N_VDD_M1_s PM_REF_INV_VDD
x_PM_REF_INV_OUT OUT N_OUT_M1_d N_OUT_M0_d PM_REF_INV_OUT
