* File: invstage1_lay.sp.INVSTAGE1_LAY.pxi
* Created: Mon Oct  9 09:24:36 2017
* 
x_PM_INVSTAGE1_LAY_OUT N_OUT_M0_g N_OUT_M1_g OUT PM_INVSTAGE1_LAY_OUT
x_PM_INVSTAGE1_LAY_IN N_IN_M1_d N_IN_M0_d IN PM_INVSTAGE1_LAY_IN
x_PM_INVSTAGE1_LAY_GND N_GND_M0_b GND N_GND_M0_s PM_INVSTAGE1_LAY_GND
x_PM_INVSTAGE1_LAY_VDD N_VDD_M1_b VDD N_VDD_M1_s PM_INVSTAGE1_LAY_VDD
